### ISSUE TITLE
Localization question

### ISSUE THREAD

**Issue by guillotemanija** [JeromeTan1997/LocationPicker#22]
Hi there, awesome location picker!

How can I change the language the addresses are written in. All addresses are in English, but I would like them to be in Spanish.

Thank you

**Comment by zhuorantan** [comment]
The language depends on locale setting of the device because adresses are provided by [this API](https://developer.apple.com/reference/corelocation/clgeocoder/1423621-reversegeocodelocation). If you configured language setting properly and still can't get addresses in Spanish, then Apple may hasn't provided Spanish addresses yet.

**Comment by guillotemanija** [comment]
Thank you for your answer. I will look into that
